//Í¼Æ¬Î»ÖÃÉùÃ÷ 


#define			Pic_WAITING_KEY  							0 + Picture_Language
#define			Pic_CHECK_FUN  								1 + Picture_Language
#define			Pic_FACE_WORK  								2 + Picture_Language

#define			Pic_CUT_TIME1 								3 + Picture_Language
#define			Pic_CUT_TIME2 				 			  4 + Picture_Language
#define			Pic_CUT_TIME3 				 			  5 + Picture_Language
#define			Pic_CUT_TIME4 				        6 + Picture_Language

#define			Pic_CUT_KP_GEAR1 				 		  7 + Picture_Language
#define			Pic_CUT_KP_GEAR2 				 		  8 + Picture_Language
#define			Pic_CUT_KP_GEAR3 				      9 + Picture_Language
#define			Pic_CUT_KP_GEAR4 		         10 + Picture_Language

#define			Pic_CUT_FLOW_GEAR1 				 		 11 + Picture_Language
#define			Pic_CUT_FLOW_GEAR2 				 		 12 + Picture_Language
#define			Pic_CUT_FLOW_GEAR3 				     13 + Picture_Language
#define			Pic_CUT_FLOW_GEAR4 		         14 + Picture_Language


#define			Pic_ADVANCED_SETTINGS				 15 + Picture_Language
#define			Pic_WRITE_CARD					     16 + Picture_Language
#define			Pic_ADJUST_KP								 17 + Picture_Language
#define			Pic_ADJUST_FLOW							 18 + Picture_Language
#define			Pic_FACE_WORK_DOWN					 19 + Picture_Language
#define			Pic_WATER_WARNING					 	 20 + Picture_Language

#define			Pic_PAOPAO_WORK				 			 21 + Picture_Language
#define			Pic_CUT_O2_GEAR1 				 		 22 + Picture_Language
#define			Pic_CUT_O2_GEAR2 				 		 23 + Picture_Language
#define			Pic_CUT_H2_GEAR1 				 		 24 + Picture_Language
#define			Pic_CUT_H2_GEAR2 				 		 25 + Picture_Language





/*
#define			Pic_CHECK_IC_CARD  						21 + Picture_Language
#define			Pic_INPUT_NUM									2 + Picture_Language
#define			Pic_INPUT_AGE									3 + Picture_Language

#define			Pic_BODY_WORK  								5 + Picture_Language
#define			Pic_BODY_WORK_DOWN  					6 + Picture_Language

#define			Pic_CUT_POWER1 								29 + Picture_Language
#define			Pic_CUT_POWER2 				 			 120 + Picture_Language
#define			Pic_CUT_POWER3 				 			 11 + Picture_Language
#define			Pic_CUT_POWER4 				       12 + Picture_Language
#define			Pic_CHECK_LANGUAGE 		       13 + Picture_Language
#define			Pic_CHECK_LANGUAGE_DOWN      14 + Picture_Language
#define			Pic_ADJUST_POWER				     25 + Picture_Language

#define			Pic_ADVANCED_SETTINGS_DOWN	 17 + Picture_Language

#define			Pic_CUT_BODY_POWER1					 19 + Picture_Language
#define			Pic_CUT_BODY_POWER2					 20 + Picture_Language
#define			Pic_CUT_BODY_POWER3					 21 + Picture_Language
#define			Pic_CUT_BODY_POWER4					 22 + Picture_Language
*/


#define			AD_BODY_POWER_GEAR				50
#define			AD_FACE_POWER_GEAR1				51
#define			AD_FACE_POWER_GEAR2				52
#define			AD_LANGUAGE								100
#define			AD_MAX_GEAR_DATA_HEADLE1	101
#define			AD_MIN_GEAR_DATA_HEADLE1	102
#define			AD_MAX_GEAR_DATA_HEADLE2	103
#define			AD_MIN_GEAR_DATA_HEADLE2	104
#define			AD_MAX_GEAR_DATA_HEADLE3	105
#define			AD_MIN_GEAR_DATA_HEADLE3	106



#define			ADH_FLOW_CYCLE_DATA		10
#define			ADL_FLOW_CYCLE_DATA		11

#define			ADH_FLOW_MAX_DATA		  12
#define			ADL_FLOW_MAX_DATA		  13

#define			ADH_FLOW_MIN_DATA		  14
#define			ADL_FLOW_MIN_DATA		  15

#define			ADH_MAX_KP_DATA			  16
#define			ADL_MAX_KP_DATA			  17

#define			ADH_MIN_KP_DATA			  18
#define			ADL_MIN_KP_DATA			  19


















